global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "trainshop-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:3000"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
